import type { Metadata } from 'next';
import { Navbar } from './components/Navbar/Navbar';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='da'>
      <Navbar
        navItems={[
          { name: 'opskrifter', link: '/opskrifter' },
          { name: 'Ugens madplan', link: '/madplan' },
          { name: 'om Mormor', link: '/om-mormor' },
        ]}
      />
      {children}
    </html>
  );
}
